; Script generated by Antigravity for Mizan AI Video Studio
#define MyAppName "Mizan AI Video Studio"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "Mizan"
#define MyAppURL "https://www.facebook.com/Agpt2"
#define MyAppExeName "MizanAIStudio.exe"

[Setup]
AppId={{5E97D452-9F1C-4B9A-99B2-9F16E8C2B3A1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=
OutputDir=d:\Ai By Mizan\installer_output
OutputBaseFilename=Mizan_AI_Video_Studio_Setup
SetupIconFile=d:\Ai By Mizan\assets\app_icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
UninstallDisplayIcon={app}\assets\app_icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; Main Executable and Launcher Scripts
Source: "d:\Ai By Mizan\MizanAIStudio.exe"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\run_app.bat"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\setup_and_run.bat"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\setup_and_run.ps1"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\app.py"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\config.py"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\requirements.txt"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\.env.example"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full
Source: "d:\Ai By Mizan\README.md"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-full

; Directories and Assets
Source: "d:\Ai By Mizan\agents\*"; DestDir: "{app}\agents"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: users-full
Source: "d:\Ai By Mizan\core\*"; DestDir: "{app}\core"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: users-full
Source: "d:\Ai By Mizan\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: users-full
Source: "d:\Ai By Mizan\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: users-full
Source: "d:\Ai By Mizan\runtime\*"; DestDir: "{app}\runtime"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: users-full
Source: "d:\Ai By Mizan\.streamlit\*"; DestDir: "{app}\.streamlit"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: users-full

[Dirs]
Name: "{app}"; Permissions: users-full
Name: "{app}\output"; Permissions: users-full
Name: "{app}\temp"; Permissions: users-full
Name: "{app}\runtime"; Permissions: users-full

[Icons]
Name: "{autoprograms}\{#MyAppName}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\app_icon.ico"
Name: "{autoprograms}\{#MyAppName}\Output Videos"; Filename: "{app}\output"
Name: "{autoprograms}\{#MyAppName}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\app_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
